blog:
  avatar: "https://avatars.githubusercontent.com/u/195545824?v=4"
  name: "ğ€ğğŸğšğ®ğ­ğ®ğ¦ğ§"
  sname: "ç‰¹åˆ«é¡¹ç›®"
  description: "ğ•š ğ•¨ğ•’ğ•¤ ğ•¥ğ•–ğ•ğ•¡ğ• ğ•£ğ•’ğ•£ğ•ª ğŸš ğ•¦"
  favicon: "https://avatars.githubusercontent.com/u/195545824?v=4"

  theme:
    mode: "dark"
    primary_color: "#e74c3c"
    dark_bg: "#121212"
    light_bg: "#f5f7fa"

floating_menu:
  - tag: "about"
    display: "å…³äº"

special:
  top: true
  view:
    RF_Information: ""
    RF_Link: ""
    Copyright: ""
    C_Link: ""
    Total_time: "2026.01.01"
    Others: ""

templates:
  article: "article.html"
  home: "home.html"

special_tags:
  - "top"
  - "special"
  - "é¡¹ç›®"
